compatibility_date = "2022-07-22"
name = "firebase-verifier-dev"
account_id = "9ddca7c9df604668fc6d14f079b2f066" 
# node_compat = true
main = "src/index.mjs"
exclude = ["node_modules"]

[env.production]
kv_namespaces = [
  {binding="backbank",id="e4609a2b6fa943aab9e44185293dae3a"}
]
name = "firebase-verifier"
route = { pattern = "https://vault-co.in/firebase_verifier", zone_id = "c30033984b7be7d945e5fdaf293c6220" }
